/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package org.netbeans.modules.nbexpose;

import java.util.Comparator;
import java.util.Date;
import java.util.ResourceBundle;
import javax.swing.event.ListSelectionEvent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.netbeans.modules.nbexpose//Expose2//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ExposeTopComponent",
        iconBase="/org/netbeans/modules/nbexpose/icon16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "org.netbeans.modules.nbexpose.ExposeTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ExposeAction",
        preferredID = "ExposeTopComponent"
)

public final class ExposeTopComponent extends TopComponent {

    private static ExposeTopComponent instance;
    
    protected static TopComponent findInstance() {
        if ( instance!=null ) return instance;
        synchronized (ExposeTopComponent.class) {
            if ( instance!=null ) return instance;
            instance= new ExposeTopComponent();
        }
        return instance;
    }

    public ExposeTableModel model;
    public TableMouseAdapter mia;
    
    public ExposeTopComponent() {
        initComponents();
        jTable1.setDefaultRenderer( TopComponent.class, new IconTableCellRenderer() );
        jTable1.setDefaultRenderer( Date.class, new DateCellRenderer() );
        
        ResourceBundle bundle= java.util.ResourceBundle.getBundle("org/netbeans/modules/nbexpose/Bundle");
        setName( bundle.getString("CTL_ExposeTopComponent") );
        setToolTipText( bundle.getString("HINT_ExposeTopComponent") );
        
        model= new ExposeTableModel( this );
        TableSorter sorter= new TableSorter( model );
        
        sorter.setColumnComparator(TopComponent.class, (Comparator<TopComponent>) (TopComponent o1, TopComponent o2) -> {
            String s1= Util.getLabelFor(o1).toLowerCase();
            String s2= Util.getLabelFor(o2).toLowerCase();
            return s1.compareTo( s2 );
        });
                
        jTable1.setModel( sorter );
        sorter.setTableHeader( jTable1.getTableHeader() );

        jTable1.getColumnModel().getColumn(0).setMaxWidth(20);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);

        jTable1.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            int n= jTable1.getSelectedRows().length;
            closeSelectedButton.setText("Close "+n+" Selected Items" );
        });
        mia= new TableMouseAdapter();
        jTable1.addMouseListener( mia );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        keepCheckedButton = new javax.swing.JButton();
        closeCheckedItemsButton = new javax.swing.JButton();
        closeSelectedButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.openide.awt.Mnemonics.setLocalizedText(keepCheckedButton, org.openide.util.NbBundle.getMessage(ExposeTopComponent.class, "ExposeTopComponent.keepCheckedButton.text")); // NOI18N
        keepCheckedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keepCheckedButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(closeCheckedItemsButton, org.openide.util.NbBundle.getMessage(ExposeTopComponent.class, "ExposeTopComponent.closeCheckedItemsButton.text")); // NOI18N
        closeCheckedItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCheckedItemsButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(closeSelectedButton, org.openide.util.NbBundle.getMessage(ExposeTopComponent.class, "ExposeTopComponent.closeSelectedButton.text")); // NOI18N
        closeSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSelectedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(keepCheckedButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeCheckedItemsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeSelectedButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keepCheckedButton)
                    .addComponent(closeCheckedItemsButton)
                    .addComponent(closeSelectedButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeCheckedItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCheckedItemsButtonActionPerformed
        model.actionsProvider.closeSelected();
    }//GEN-LAST:event_closeCheckedItemsButtonActionPerformed

    private void keepCheckedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keepCheckedButtonActionPerformed
        model.actionsProvider.dontCloseSelected();
    }//GEN-LAST:event_keepCheckedButtonActionPerformed

    private void closeSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSelectedButtonActionPerformed
        mia.closeSelected();
    }//GEN-LAST:event_closeSelectedButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeCheckedItemsButton;
    private javax.swing.JButton closeSelectedButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keepCheckedButton;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
}
